version: "3"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    links:
      - mongo_test
  mongo_test:
    container_name: mongo_test
    image: mongo
    volumes:
      - ./data:/data/db/test
    logging:
        driver: none
