version: "3"
services:
  customers_app:
    container_name: customers
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    logging:
        driver: none
